#pragma once
#include "PhysicsObject.h"
#include "glm/vec4.hpp"

class Rigidbody;

class Plane :
    public PhysicsObject
{

public:
    Plane(glm::vec2 normal, float distance);
    ~Plane() {};

    virtual void FixedUpdate(glm::vec2 gravity, float timeStep);
    virtual void Draw();
    virtual void ResetPosition() {};

    glm::vec2 GetNormal(); //return plane's normal
    float GetDistance(); //return distance to origin

    void ResolveCollision(Rigidbody* actor2, glm::vec2 contact); //calculate force generated by collision, then apply force to other actor (planes are static)

protected:
    glm::vec2 m_normal;
    float m_distanceToOrigin;
    glm::vec4 m_colour;
};

